### ISSUE TITLE
change the team.vue page in page section 

### ISSUE THREAD

**Issue by hiren14** [code22hives/code_hives#4]
hey team in this issue you have create a new file called [code_hives](https://github.com/code22hives/code_hives)/[components/Team2021Section](https://github.com/code22hives/code_hives/tree/main/components/Team2021Section.vue)
copy the code of above link and create a new file in it called Team2022Section and paste the code 

[copy the code of above link and create a new file in it called Team2022Section and paste the code ](https://github.com/code22hives/code_hives/blob/main/components/Team2021Section.vue#:~:text=%3CHashHeader%20title%3D%22TEAM%22%20/%3E
)

[change to tittle="member"and
 add new join member data there make sure that img should be in new folder called](https://github.com/code22hives/code_hives/tree/main/assets/Team/Team2022)

[like this change data](https://github.com/code22hives/code_hives/blob/main/components/Team2021Section.vue#:~:text=name%3A%20%22Sachin,%7D2C)

**Comment by code22hives** [comment]
Done

**Comment by code22hives** [comment]
Ok done
